default:
  seed: 0
  wrapper:
    pipeline:
      [
        "ActionNoise",
        "ImageNoise",
        "TimeLimit",
        "DiscreteAction",
        "DepthProcess",
        "DSA",
        "VirtualClutch",
        "FSM",
        "OBS",
      ]
    ActionSmooth: { skip: true, window: 3, smooth_type: ema }
    DSA:
      {
        zoom_box_obj: psm1,
        encode_type: general_simple2,
        cv_interpolate: area,
        zoom_box_fix_length_ratio: 0.5,
        encoding_id_needle: 60,
        encoding_id_psm1: 130,
        encoding_id_zoom_box: 30,
        zoom_movement_type: continuous,
        dense_reward: false,
      }
    VirtualClutch: { start: 6 }
    ActionNoise: { noise_scale: 0.0 }
    DiscreteAction: { action_scale: 0.2 }
    TimeLimit: { max_timestep: 200 }
    DepthProcess: { skip: true, uncert_scale: 1.0, eval: false }
    FSM: { arg: 0 , ensure_norm_reward: false,  dsa_out_zoom_anamaly: false,}
    OBS:
      {
        image_obs_key: ["dsa"],
        vector_obs_key: ["gripper_state", "fsm_state"],
        direct_map_key: ["fsm_state"],
        direct_render_key: ["rgb", "depth"],
        is_vector2image: true,
        image_resize: [64, 64],
        vector2image_type: "row",
        action_insertion_anamaly: false,
        cv_interpolate: "area"
      }
    ImageNoise:
      {
        skip: true,
        pns_noise_amount: 0.05,
        pns_noise_balance: 0.5,
        gaussian_blur_kernel: 3,
        gaussian_blur_sigma: 0.8,
        cutout_all_amount_range: [0.6, 1.0],
        cutout_depth_amount_range: [0.7, 1.0],
        cutout_line_num_low: 3,
        cutout_line_num_high: 10,
      }
  task_name: needle_pick
  embodied_name: SurrolEnv
  embodied:
    SurrolEnv:
      pybullet_gui: false
      cam_width: 600
      cam_height: 600
      mask_background_id: -3
      depth_remap_range: 0.1
      depth_remap_range_noise: 0.0
      depth_remap_center_noise: 0.0
      cam_target_noise: 0.0
      cam_distance_noise: 0.0
      cam_yaw_noise: 0.0
      cam_pitch_noise: 0.0
      cam_roll_noise: 0.0
      cam_up_axis_noise: 0.0
      background_texture_dir: ""
      cam_mode: "rgbdm"
      cam_num: 1
      no_depth_link: false
      mask_except_gripper: false
      reward_done_success: 1
      reward_done_fail: -0.1
      reward_prog_norm: -0.001
      reward_prog_abnorm_1: -0.01
      reward_prog_abnorm_2: -0.001
      reward_prog_abnorm_3: -0.001
      disturbance_scale: 0.0
      cam_dynamic_noise_scale: 0.0
      dr_scale_train: 1
      dr_scale_eval: 1
      needle_pick:
        fix_goal: true
        noise_scale: 1.0
        done_z_thres: 0.2
        init_pose_ratio_low_gripper: [-0.5, -0.5, -0.5, -0.9]
        init_pose_ratio_high_gripper: [0.5, 0.5, 0.5, 0.9]
        init_pose_ratio_low_needle: [-0.5, -0.5, 0.1, -0.99]
        init_pose_ratio_high_needle: [0.5, 0.5, 0.5, 0.99]
        random_obj_vis: false
        depth_distance: 0.3
      gauze_retrieve:
        fix_goal: true
        noise_scale: 1.0
        done_z_thres: 0.2
        init_pose_ratio_low_gripper: [-0.5, -0.5, -0.5, -0.9]
        init_pose_ratio_high_gripper: [0.5, 0.5, 0.5, 0.9]
        init_pose_ratio_low_stuff: [-0.5, -0.5, 0.1, -0.99, -0.99, -0.99]
        init_pose_ratio_high_stuff: [0.5, 0.5, 0.5, 0.99, 0.99, 0.99]
        random_obj_vis: false
        depth_distance: 0.3
      peg_transfer:
        fix_goal: true
        noise_scale: 1.0
        done_z_thres: 0.2
        init_pose_ratio_low_gripper: [-0.5, -0.5, -0.5, -0.9]
        init_pose_ratio_high_gripper: [0.5, 0.5, 0.5, 0.9]
        init_pose_ratio_low_stuff: [-0.5, -0.5, 0.1, -0.99]
        init_pose_ratio_high_stuff: [0.5, 0.5, 0.5, 0.99]
        random_obj_vis: false
        depth_distance: 0.3
      grasp_any:
        stuff_name: needle
        fix_goal: true
        noise_scale: 1.0
        done_z_thres: 0.2
        init_pose_ratio_low_gripper: [-0.5, -0.5, -0.5, -0.9]
        init_pose_ratio_high_gripper: [0.5, 0.5, 0.5, 0.9]
        init_pose_ratio_low_stuff: [-0.5, -0.5, 0.1, -0.99]
        init_pose_ratio_high_stuff: [0.5, 0.5, 0.5, 0.99]
        random_obj_vis: false
        depth_distance: 0.3
        on_plane: true
        oracle_pos_thres: 1e-3
        oracle_rot_thres: 3e-1
      grasp_any_v2:
        stuff_name: needle
        fix_goal: true
        noise_scale: 1.0
        done_z_thres: 0.2
        init_pose_ratio_low_gripper: [-0.5, -0.5, -0.5, -0.9]
        init_pose_ratio_high_gripper: [0.5, 0.5, 0.5, 0.9]
        init_pose_ratio_low_stuff: [-0.5, -0.5, 0.1, -0.99]
        init_pose_ratio_high_stuff: [0.5, 0.5, 0.5, 0.99]
        random_obj_vis: false
        depth_distance: 0.3
        on_plane: true
        oracle_pos_thres: 1e-3
        oracle_rot_thres: 3e-1
    dVRKEnv:
      grasp_any:
        arm_names: ["PSM1"]
        rgbd_device: "rs435"
        oracle_device: "ds4"
        ws_x: [-0.1, 0.1]
        ws_y: [-0.1, 0.1]
        ws_z: [-0.24, 0.0]
        psm_reset_q: [0.0, 0.0, 0.12, 0.0, 0.0, 0.0]
        psm_open_gripper_deg: 40.0
        psm_init_gripper_quat: [7.07106781e-01, 7.07106781e-01, 0.0, 0.0]
        psm_init_pose_low_gripper: [-0.5, -0.5, -0.5, -0.9]
        psm_init_pose_high_gripper: [0.5, 0.5, 0.5, 0.9]
        psm_max_step_pos: 0.01
        psm_max_step_rot: 20.0
        cam_image_height: 600
        cam_image_width: 600
        cam_depth_remap_center: 0.3
        cam_depth_remap_range: 0.1
        dvrk_cal_file: ""
        cam_segment_tool: ""
        cam_segment_model_dir: ""
        cam_cal_file: ""
        done_cal_file: ""
        cam_mask_noisy_link: true

gas_surrol:
  task_name: grasp_any
  embodied.SurrolEnv.cam_target_noise: 1e-2
  embodied.SurrolEnv.cam_distance_noise: 5e-2
  embodied.SurrolEnv.cam_pitch_noise: 10e0
  embodied.SurrolEnv.cam_roll_noise: 11e0
  embodied.SurrolEnv.cam_up_axis_noise: 5e0
  embodied.SurrolEnv.depth_remap_range_noise: 1e-2
  embodied.SurrolEnv.depth_remap_center_noise: 1e-2
  embodied.SurrolEnv.no_depth_link: true
  embodied.SurrolEnv.needle_pick.init_pose_ratio_low_gripper: [-0.9, -0.9, -0.8, -0.9]
  embodied.SurrolEnv.needle_pick.init_pose_ratio_high_gripper: [0.9, 0.9, 0.9, 0.9]
  embodied.SurrolEnv.needle_pick.init_pose_ratio_low_needle: [-0.5, -0.7, 0.1, -0.99]
  embodied.SurrolEnv.needle_pick.init_pose_ratio_high_needle: [0.5, 0.7, 0.5, 0.99]
  embodied.SurrolEnv.reward_prog_abnorm_1: -0.01
  embodied.SurrolEnv.reward_prog_abnorm_2: -0.01 # sliding
  embodied.SurrolEnv.reward_prog_abnorm_3: -0.005 # gripper toggling | dsa out
  embodied.SurrolEnv.reward_done_fail: -0.1
  embodied.SurrolEnv.reward_prog_norm: -0.001
  embodied.SurrolEnv.reward_done_success: 1
  embodied.SurrolEnv.grasp_any.init_pose_ratio_low_gripper: [-0.9, -0.9, -0.8, -0.9]
  embodied.SurrolEnv.grasp_any.init_pose_ratio_high_gripper: [0.9, 0.9, 0.9, 0.9]
  embodied.SurrolEnv.grasp_any.init_pose_ratio_low_stuff: [-0.8, -0.8, 0.1, -0.99,-0.99,-0.99]
  embodied.SurrolEnv.grasp_any.init_pose_ratio_high_stuff: [0.8, 0.8, 0.5, 0.99, 0.99, 0.99]
  embodied.SurrolEnv.disturbance_scale: 0.01
  embodied.SurrolEnv.grasp_any.stuff_name: "any"
  embodied.SurrolEnv.cam_dynamic_noise_scale: 0.1
  wrapper.DSA.zoom_box_fix_length_ratio: 0.3
  wrapper.DSA.encode_type: general_simple3
  wrapper.ImageNoise.skip: false
  wrapper.ImageNoise.cutout_all_amount_range: [0.54, 1.0]
  wrapper.ImageNoise.cutout_depth_amount_range: [1.0, 1.0]
  wrapper.ImageNoise.cutout_line_num_low: 0
  wrapper.ImageNoise.cutout_line_num_high: 0
  wrapper.FSM.dsa_out_zoom_anamaly: true
  wrapper.TimeLimit: { max_timestep: 300 }
  wrapper.ActionNoise.noise_scale: 0.04
  wrapper.OBS.vector2image_type: "square"
  wrapper.DepthProcess.skip: false
  wrapper.DepthProcess.uncert_scale: 1.5

dvrk:
  embodied_name: dVRKEnv
  embodied.dVRKEnv.grasp_any.dvrk_cal_file: "./data/dvrk_cal/dvrk_cal.yaml"
  embodied.dVRKEnv.grasp_any.cam_segment_tool: "track_any"
  embodied.dVRKEnv.grasp_any.cam_segment_model_dir: "./data/dvrk_cal/color_seg_cal.yaml"
  wrapper.DepthProcess.eval: true
  wrapper.ImageNoise.skip: true
  wrapper.ActionNoise.noise_scale: 0.0
  wrapper.TimeLimit.max_timestep: 300

########## other baselines##################33
raw:
  wrapper.DSA.encode_type: raw
no_depth_estimation:
  wrapper.DepthProcess.skip: true

no_clutch:
  wrapper.VirtualClutch.start: 0

no_dm: # no domain randomization
  embodied.SurrolEnv.cam_target_noise: 0.0
  embodied.SurrolEnv.cam_distance_noise: 0.0
  embodied.SurrolEnv.cam_pitch_noise: 0.0
  embodied.SurrolEnv.cam_roll_noise: 0.0
  embodied.SurrolEnv.cam_up_axis_noise: 0.0
  embodied.SurrolEnv.depth_remap_range_noise: 0.0
  embodied.SurrolEnv.depth_remap_center_noise: 0.0
  wrapper.ImageNoise.skip: true
  embodied.SurrolEnv.disturbance_scale: 0.00
  wrapper.ActionNoise.noise_scale: 0.00

no_dr:
  embodied.SurrolEnv.dr_scale_train: 0

no_cam_noisy_mask:
  embodied.dVRKEnv.grasp_any.cam_mask_noisy_link: False

image_noise_on:
  wrapper.ImageNoise.skip: false

action_noise_on:
  wrapper.ActionNoise.noise_scale: 0.04
###############



gasv2_surrol:
  task_name: grasp_any_v2
  embodied.SurrolEnv.cam_target_noise: 1e-2
  embodied.SurrolEnv.cam_distance_noise: 5e-2
  embodied.SurrolEnv.cam_pitch_noise: 10e0
  embodied.SurrolEnv.cam_roll_noise: 11e0
  embodied.SurrolEnv.cam_up_axis_noise: 5e0
  embodied.SurrolEnv.depth_remap_range_noise: 1e-2
  embodied.SurrolEnv.depth_remap_center_noise: 1e-2
  embodied.SurrolEnv.no_depth_link: true
  embodied.SurrolEnv.needle_pick.init_pose_ratio_low_gripper: [-0.9, -0.9, -0.8, -0.9]
  embodied.SurrolEnv.needle_pick.init_pose_ratio_high_gripper: [0.9, 0.9, 0.9, 0.9]
  embodied.SurrolEnv.needle_pick.init_pose_ratio_low_needle: [-0.5, -0.7, 0.1, -0.99]
  embodied.SurrolEnv.needle_pick.init_pose_ratio_high_needle: [0.5, 0.7, 0.5, 0.99]
  embodied.SurrolEnv.reward_prog_abnorm_1: -0.01
  embodied.SurrolEnv.reward_prog_abnorm_2: -0.01 # sliding
  embodied.SurrolEnv.reward_prog_abnorm_3: -0.005 # gripper toggling | dsa out
  embodied.SurrolEnv.reward_done_fail: -0.1
  embodied.SurrolEnv.reward_prog_norm: -0.001
  embodied.SurrolEnv.reward_done_success: 1
  embodied.SurrolEnv.grasp_any_v2.init_pose_ratio_low_gripper: [-0.9, -0.9, -0.8, -0.9]
  embodied.SurrolEnv.grasp_any_v2.init_pose_ratio_high_gripper: [0.9, 0.9, 0.9, 0.9]
  embodied.SurrolEnv.grasp_any_v2.init_pose_ratio_low_stuff: [-0.8, -0.8, 0.1, -0.99,-0.99,-0.99]
  embodied.SurrolEnv.grasp_any_v2.init_pose_ratio_high_stuff: [0.8, 0.8, 0.5, 0.99, 0.99, 0.99]
  embodied.SurrolEnv.grasp_any_v2.stuff_name: "any"
  embodied.SurrolEnv.disturbance_scale: 0.01
  embodied.SurrolEnv.cam_dynamic_noise_scale: 0.1
  wrapper.DSA.zoom_box_fix_length_ratio: 0.3
  wrapper.DSA.encode_type: general_simple3
  wrapper.ImageNoise.skip: false
  wrapper.ImageNoise.cutout_all_amount_range: [0.54, 1.0]
  wrapper.ImageNoise.cutout_depth_amount_range: [1.0, 1.0]
  wrapper.ImageNoise.cutout_line_num_low: 0
  wrapper.ImageNoise.cutout_line_num_high: 0
  wrapper.FSM.dsa_out_zoom_anamaly: true
  wrapper.TimeLimit: { max_timestep: 300 }
  wrapper.ActionNoise.noise_scale: 0.04
  wrapper.OBS.vector2image_type: "square"
  wrapper.DepthProcess.skip: false
  wrapper.DepthProcess.uncert_scale: 1.5


gui: 
  embodied.SurrolEnv.pybullet_gui: true

################################################
## other setting that might not work
dsa_decompose:
  wrapper.DSA.encode_type: decompose
  wrapper.OBS.cv_interpolate: area
  wrapper.OBS.vector2image_type: "row"
  wrapper.FSM.ensure_norm_reward: true
  wrapper.DSA.dense_reward: true

grasp_standing_needle:
  embodied.SurrolEnv.grasp_any.on_plane: false
  embodied.SurrolEnv.grasp_any.oracle_pos_thres: 15e-4
  wrapper.ActionNoise.noise_scale: 0.01

#########################################

